# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/c/Study/source/2026/Add_Norm_AXI/ADD_NORM_AXI.srcs/layernorm_axi_wrapper_1_0/src/axis_master_vip_0/axis_master_vip_0.xci
# IP: The module: 'axis_master_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Study/source/2026/Add_Norm_AXI/ADD_NORM_AXI.srcs/layernorm_axi_wrapper_1_0/src/axis_master_vip_0/axis_master_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_master_vip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/c/Study/source/2026/Add_Norm_AXI/ADD_NORM_AXI.srcs/layernorm_axi_wrapper_1_0/src/axis_master_vip_0/axis_master_vip_0.xci
# IP: The module: 'axis_master_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Study/source/2026/Add_Norm_AXI/ADD_NORM_AXI.srcs/layernorm_axi_wrapper_1_0/src/axis_master_vip_0/axis_master_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_master_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
