# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.srcs/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/layernorm_dma_system_axi_smc_1_1.xci
# IP: The module: 'layernorm_dma_system_axi_smc_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/bd_6088.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_0/bd_6088_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_2/bd_6088_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_3/bd_6088_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_4/bd_6088_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_5/bd_6088_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_6/bd_6088_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_7/bd_6088_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_8/bd_6088_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_9/bd_6088_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_10/bd_6088_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_11/bd_6088_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_12/bd_6088_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_13/bd_6088_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_14/bd_6088_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_15/bd_6088_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_16/bd_6088_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_17/bd_6088_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_18/bd_6088_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_19/bd_6088_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_20/bd_6088_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_21/bd_6088_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_22/bd_6088_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_23/bd_6088_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_24/bd_6088_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_25/bd_6088_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_26/bd_6088_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_27/bd_6088_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_28/bd_6088_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_29/bd_6088_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_30/bd_6088_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_31/bd_6088_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_32/bd_6088_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_33/bd_6088_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_34/bd_6088_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_35/bd_6088_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_36/bd_6088_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_37/bd_6088_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_38/bd_6088_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_39/bd_6088_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_2/bd_6088_arinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_3/bd_6088_rinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_4/bd_6088_awinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_5/bd_6088_winsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_6/bd_6088_binsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_7/bd_6088_aroutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_8/bd_6088_routsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_9/bd_6088_awoutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_10/bd_6088_woutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_11/bd_6088_boutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_12/bd_6088_arni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_13/bd_6088_rni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_14/bd_6088_awni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_15/bd_6088_wni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_16/bd_6088_bni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_20/bd_6088_s00a2s_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_21/bd_6088_sarn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_22/bd_6088_srn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_23/bd_6088_sawn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_24/bd_6088_swn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_25/bd_6088_sbn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_26/bd_6088_m00s2a_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_27/bd_6088_m00arn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_28/bd_6088_m00rn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_29/bd_6088_m00awn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_30/bd_6088_m00wn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_31/bd_6088_m00bn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_33/bd_6088_m01s2a_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_34/bd_6088_m01arn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_35/bd_6088_m01rn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_36/bd_6088_m01awn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_37/bd_6088_m01wn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_38/bd_6088_m01bn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_axi_smc_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_axi_smc_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.srcs/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/layernorm_dma_system_axi_smc_1_1.xci
# IP: The module: 'layernorm_dma_system_axi_smc_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/bd_6088.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_0/bd_6088_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_2/bd_6088_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_3/bd_6088_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_4/bd_6088_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_5/bd_6088_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_6/bd_6088_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_7/bd_6088_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_8/bd_6088_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_9/bd_6088_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_10/bd_6088_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_11/bd_6088_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_12/bd_6088_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_13/bd_6088_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_14/bd_6088_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_15/bd_6088_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_16/bd_6088_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_17/bd_6088_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_18/bd_6088_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_19/bd_6088_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_20/bd_6088_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_21/bd_6088_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_22/bd_6088_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_23/bd_6088_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_24/bd_6088_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_25/bd_6088_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_26/bd_6088_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_27/bd_6088_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_28/bd_6088_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_29/bd_6088_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_30/bd_6088_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_31/bd_6088_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_32/bd_6088_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_33/bd_6088_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_34/bd_6088_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_35/bd_6088_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_36/bd_6088_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_37/bd_6088_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_38/bd_6088_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_39/bd_6088_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_1/bd_6088_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_2/bd_6088_arinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_3/bd_6088_rinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_4/bd_6088_awinsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_5/bd_6088_winsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_6/bd_6088_binsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_7/bd_6088_aroutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_8/bd_6088_routsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_9/bd_6088_awoutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_10/bd_6088_woutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_11/bd_6088_boutsw_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_12/bd_6088_arni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_13/bd_6088_rni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_14/bd_6088_awni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_15/bd_6088_wni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_16/bd_6088_bni_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_20/bd_6088_s00a2s_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_21/bd_6088_sarn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_22/bd_6088_srn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_23/bd_6088_sawn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_24/bd_6088_swn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_25/bd_6088_sbn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_26/bd_6088_m00s2a_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_27/bd_6088_m00arn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_28/bd_6088_m00rn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_29/bd_6088_m00awn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_30/bd_6088_m00wn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_31/bd_6088_m00bn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_33/bd_6088_m01s2a_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_34/bd_6088_m01arn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_35/bd_6088_m01rn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_36/bd_6088_m01awn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_37/bd_6088_m01wn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/bd_0/ip/ip_38/bd_6088_m01bn_0_ooc.xdc

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_axi_smc_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_1_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_axi_smc_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
