# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/ps_dma_ip_axi_smc_0.xci
# IP: The module: 'ps_dma_ip_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/bd_8609.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_0/bd_8609_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_2/bd_8609_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_3/bd_8609_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_4/bd_8609_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_5/bd_8609_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_6/bd_8609_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_7/bd_8609_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_8/bd_8609_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_9/bd_8609_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_10/bd_8609_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_11/bd_8609_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_12/bd_8609_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_13/bd_8609_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_14/bd_8609_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_15/bd_8609_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_16/bd_8609_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_17/bd_8609_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_18/bd_8609_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_19/bd_8609_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_20/bd_8609_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_21/bd_8609_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_22/bd_8609_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_23/bd_8609_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_24/bd_8609_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_25/bd_8609_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_26/bd_8609_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_2/bd_8609_arsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_3/bd_8609_rsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_4/bd_8609_awsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_5/bd_8609_wsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_6/bd_8609_bsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_10/bd_8609_s01a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_11/bd_8609_sarn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_12/bd_8609_srn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_16/bd_8609_s02a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_17/bd_8609_sawn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_18/bd_8609_swn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_19/bd_8609_sbn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_20/bd_8609_m00s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_21/bd_8609_m00arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_22/bd_8609_m00rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_23/bd_8609_m00awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_24/bd_8609_m00wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_25/bd_8609_m00bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/ps_dma_ip_axi_smc_0.xci
# IP: The module: 'ps_dma_ip_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/bd_8609.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_0/bd_8609_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_2/bd_8609_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_3/bd_8609_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_4/bd_8609_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_5/bd_8609_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_6/bd_8609_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_7/bd_8609_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_8/bd_8609_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_9/bd_8609_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_10/bd_8609_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_11/bd_8609_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_12/bd_8609_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_13/bd_8609_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_14/bd_8609_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_15/bd_8609_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_16/bd_8609_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_17/bd_8609_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_18/bd_8609_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_19/bd_8609_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_20/bd_8609_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_21/bd_8609_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_22/bd_8609_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_23/bd_8609_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_24/bd_8609_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_25/bd_8609_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_26/bd_8609_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_1/bd_8609_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_2/bd_8609_arsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_3/bd_8609_rsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_4/bd_8609_awsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_5/bd_8609_wsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_6/bd_8609_bsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_10/bd_8609_s01a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_11/bd_8609_sarn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_12/bd_8609_srn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_16/bd_8609_s02a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_17/bd_8609_sawn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_18/bd_8609_swn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_19/bd_8609_sbn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_20/bd_8609_m00s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_21/bd_8609_m00arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_22/bd_8609_m00rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_23/bd_8609_m00awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_24/bd_8609_m00wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/bd_0/ip/ip_25/bd_8609_m00bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
