


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axis_master_vip_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axis_master_vip_0_VIP_INTERFACE_MODE     = 0;
      parameter axis_master_vip_0_VIP_SIGNAL_SET         = 8'b01110011;
      parameter axis_master_vip_0_VIP_DATA_WIDTH         = 512;
      parameter axis_master_vip_0_VIP_ID_WIDTH           = 1;
      parameter axis_master_vip_0_VIP_DEST_WIDTH         = 1;
      parameter axis_master_vip_0_VIP_USER_WIDTH         = 0;
      parameter axis_master_vip_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter axis_master_vip_0_VIP_HAS_TREADY         = 1;
      parameter axis_master_vip_0_VIP_HAS_TSTRB          = 0;
      parameter axis_master_vip_0_VIP_HAS_TKEEP          = 0;
      parameter axis_master_vip_0_VIP_HAS_TLAST          = 1;
      parameter axis_master_vip_0_VIP_HAS_ACLKEN         = 0;
      parameter axis_master_vip_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(axis_master_vip_0_VIP_SIGNAL_SET, 
                        axis_master_vip_0_VIP_DEST_WIDTH,
                        axis_master_vip_0_VIP_DATA_WIDTH,
                        axis_master_vip_0_VIP_ID_WIDTH,
                        axis_master_vip_0_VIP_USER_WIDTH, 
                        axis_master_vip_0_VIP_USER_BITS_PER_BYTE,
                        axis_master_vip_0_VIP_HAS_ARESETN) axis_master_vip_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axis_master_vip_0_mst_t  axis_master_vip_0_mst;
//      initial begin : START_axis_master_vip_0_MASTER
//        axis_master_vip_0_mst = new("axis_master_vip_0_mst", `axis_master_vip_0_PATH_TO_INTERFACE);
//        axis_master_vip_0_mst.start_master();
//      end



endpackage : axis_master_vip_0_pkg
