# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0.xci
# IP: The module: 'ps_dma_ip_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0.xci
# IP: The module: 'ps_dma_ip_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
