# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps_dma_ip/ps_dma_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip || ORIG_REF_NAME==ps_dma_ip} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_zynq_ultra_ps_e_0_0/ps_dma_ip_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_dma_ip_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_layernorm_axi_wrapper_0_0/ps_dma_ip_layernorm_axi_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_layernorm_axi_wrapper_0_0 || ORIG_REF_NAME==ps_dma_ip_layernorm_axi_wrapper_0_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_axi_dma_0_0/ps_dma_ip_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_axi_dma_0_0 || ORIG_REF_NAME==ps_dma_ip_axi_dma_0_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/ps_dma_ip_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_smartconnect_0_0 || ORIG_REF_NAME==ps_dma_ip_smartconnect_0_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_axi_smc_0/ps_dma_ip_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_axi_smc_0 || ORIG_REF_NAME==ps_dma_ip_axi_smc_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_rst_ps8_0_96M_0/ps_dma_ip_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_dma_ip_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/ps_dma_ip/ip/ps_dma_ip_xlconcat_0_0/ps_dma_ip_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_dma_ip_xlconcat_0_0 || ORIG_REF_NAME==ps_dma_ip_xlconcat_0_0} -quiet] -quiet

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ps_dma_ip_ooc.xdc
