# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.srcs/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1.xci
# IP: The module: 'layernorm_dma_system_rst_ps8_0_99M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.srcs/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1.xci
# IP: The module: 'layernorm_dma_system_rst_ps8_0_99M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_rst_ps8_0_99M_1/layernorm_dma_system_rst_ps8_0_99M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layernorm_dma_system_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
