# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "layernorm_dma_system_axi_smc_2_synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {17-179}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.cache/wt [current_project]
set_property parent.project_path /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu111:part0:1.4 [current_project]
set_property ip_repo_paths /mnt/c/Study/source/2026/Add_Norm_PYNQ/layernorm_axi_wrapper_IP_src [current_project]
update_ip_catalog
set_property ip_output_repo /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.srcs/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2.xci
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_1/bd_71fe_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_1/bd_71fe_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_2/bd_71fe_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_3/bd_71fe_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_4/bd_71fe_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_5/bd_71fe_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_6/bd_71fe_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_10/bd_71fe_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_11/bd_71fe_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_12/bd_71fe_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_16/bd_71fe_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_17/bd_71fe_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_18/bd_71fe_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_19/bd_71fe_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_23/bd_71fe_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_24/bd_71fe_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_25/bd_71fe_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_26/bd_71fe_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_27/bd_71fe_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_28/bd_71fe_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_29/bd_71fe_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_30/bd_71fe_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_31/bd_71fe_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_32/bd_71fe_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_33/bd_71fe_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/bd_0/ip/ip_34/bd_71fe_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/smartconnect.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1 -new_name layernorm_dma_system_axi_smc_2 -ip [get_ips layernorm_dma_system_axi_smc_2]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top layernorm_dma_system_axi_smc_2 -part xczu28dr-ffvg1517-2-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix layernorm_dma_system_axi_smc_2_ layernorm_dma_system_axi_smc_2.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ layernorm_dma_system_axi_smc_2_stub.v
 lappend ipCachedFiles layernorm_dma_system_axi_smc_2_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ layernorm_dma_system_axi_smc_2_stub.vhdl
 lappend ipCachedFiles layernorm_dma_system_axi_smc_2_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ layernorm_dma_system_axi_smc_2_sim_netlist.v
 lappend ipCachedFiles layernorm_dma_system_axi_smc_2_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ layernorm_dma_system_axi_smc_2_sim_netlist.vhdl
 lappend ipCachedFiles layernorm_dma_system_axi_smc_2_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp layernorm_dma_system_axi_smc_2.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips layernorm_dma_system_axi_smc_2]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all layernorm_dma_system_axi_smc_2_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef layernorm_dma_system_axi_smc_2.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file layernorm_dma_system_axi_smc_2_utilization_synth.rpt -pb layernorm_dma_system_axi_smc_2_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2.dcp /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2.dcp /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2_stub.v /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2_stub.vhdl /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2_sim_netlist.v /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.runs/layernorm_dma_system_axi_smc_2_synth_1/layernorm_dma_system_axi_smc_2_sim_netlist.vhdl /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.ip_user_files/ip/layernorm_dma_system_axi_smc_2]} {
  catch { 
    file copy -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.v /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.ip_user_files/ip/layernorm_dma_system_axi_smc_2
  }
}

if {[file isdir /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.ip_user_files/ip/layernorm_dma_system_axi_smc_2]} {
  catch { 
    file copy -force /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.gen/sources_1/bd/layernorm_dma_system/ip/layernorm_dma_system_axi_smc_2/layernorm_dma_system_axi_smc_2_stub.vhdl /mnt/c/Study/Source/2026/Add_Norm_PYNQ/layernorm_w_dma.ip_user_files/ip/layernorm_dma_system_axi_smc_2
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "layernorm_dma_system_axi_smc_2_synth_1" END { }
