# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/ps_dma_ip_smartconnect_0_0.xci
# IP: The module: 'ps_dma_ip_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/bd_bdc1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_0/bd_bdc1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_2/bd_bdc1_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_3/bd_bdc1_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_4/bd_bdc1_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_5/bd_bdc1_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_6/bd_bdc1_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_7/bd_bdc1_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_8/bd_bdc1_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_9/bd_bdc1_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_10/bd_bdc1_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_11/bd_bdc1_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_12/bd_bdc1_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_13/bd_bdc1_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_14/bd_bdc1_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_15/bd_bdc1_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_16/bd_bdc1_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_17/bd_bdc1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_18/bd_bdc1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_19/bd_bdc1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_20/bd_bdc1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_21/bd_bdc1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_22/bd_bdc1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_23/bd_bdc1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_24/bd_bdc1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_25/bd_bdc1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_26/bd_bdc1_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_27/bd_bdc1_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_28/bd_bdc1_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_29/bd_bdc1_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_30/bd_bdc1_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_31/bd_bdc1_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_32/bd_bdc1_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_33/bd_bdc1_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_34/bd_bdc1_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_35/bd_bdc1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_36/bd_bdc1_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_37/bd_bdc1_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_38/bd_bdc1_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_39/bd_bdc1_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_40/bd_bdc1_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_41/bd_bdc1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_42/bd_bdc1_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_43/bd_bdc1_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_44/bd_bdc1_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_45/bd_bdc1_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_46/bd_bdc1_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_47/bd_bdc1_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_48/bd_bdc1_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_2/bd_bdc1_arinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_3/bd_bdc1_rinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_4/bd_bdc1_awinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_5/bd_bdc1_winsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_6/bd_bdc1_binsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_7/bd_bdc1_aroutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_8/bd_bdc1_routsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_9/bd_bdc1_awoutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_10/bd_bdc1_woutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_11/bd_bdc1_boutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_12/bd_bdc1_arni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_13/bd_bdc1_rni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_14/bd_bdc1_awni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_15/bd_bdc1_wni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_16/bd_bdc1_bni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_20/bd_bdc1_s00a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_21/bd_bdc1_sarn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_22/bd_bdc1_srn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_23/bd_bdc1_sawn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_24/bd_bdc1_swn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_25/bd_bdc1_sbn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_29/bd_bdc1_s01a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_30/bd_bdc1_sarn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_31/bd_bdc1_srn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_32/bd_bdc1_sawn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_33/bd_bdc1_swn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_34/bd_bdc1_sbn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_35/bd_bdc1_m00s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_36/bd_bdc1_m00arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_37/bd_bdc1_m00rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_38/bd_bdc1_m00awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_39/bd_bdc1_m00wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_40/bd_bdc1_m00bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_42/bd_bdc1_m01s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_43/bd_bdc1_m01arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_44/bd_bdc1_m01rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_45/bd_bdc1_m01awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_46/bd_bdc1_m01wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_47/bd_bdc1_m01bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.srcs/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/ps_dma_ip_smartconnect_0_0.xci
# IP: The module: 'ps_dma_ip_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/bd_bdc1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_0/bd_bdc1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_2/bd_bdc1_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_3/bd_bdc1_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_4/bd_bdc1_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_5/bd_bdc1_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_6/bd_bdc1_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_7/bd_bdc1_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_8/bd_bdc1_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_9/bd_bdc1_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_10/bd_bdc1_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_11/bd_bdc1_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_12/bd_bdc1_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_13/bd_bdc1_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_14/bd_bdc1_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_15/bd_bdc1_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_16/bd_bdc1_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_17/bd_bdc1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_18/bd_bdc1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_19/bd_bdc1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_20/bd_bdc1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_21/bd_bdc1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_22/bd_bdc1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_23/bd_bdc1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_24/bd_bdc1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_25/bd_bdc1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_26/bd_bdc1_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_27/bd_bdc1_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_28/bd_bdc1_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_29/bd_bdc1_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_30/bd_bdc1_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_31/bd_bdc1_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_32/bd_bdc1_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_33/bd_bdc1_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_34/bd_bdc1_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_35/bd_bdc1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_36/bd_bdc1_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_37/bd_bdc1_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_38/bd_bdc1_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_39/bd_bdc1_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_40/bd_bdc1_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_41/bd_bdc1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_42/bd_bdc1_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_43/bd_bdc1_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_44/bd_bdc1_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_45/bd_bdc1_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_46/bd_bdc1_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_47/bd_bdc1_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_48/bd_bdc1_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_1/bd_bdc1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_2/bd_bdc1_arinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_3/bd_bdc1_rinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_4/bd_bdc1_awinsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_5/bd_bdc1_winsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_6/bd_bdc1_binsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_7/bd_bdc1_aroutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_8/bd_bdc1_routsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_9/bd_bdc1_awoutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_10/bd_bdc1_woutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_11/bd_bdc1_boutsw_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_12/bd_bdc1_arni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_13/bd_bdc1_rni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_14/bd_bdc1_awni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_15/bd_bdc1_wni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_16/bd_bdc1_bni_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_20/bd_bdc1_s00a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_21/bd_bdc1_sarn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_22/bd_bdc1_srn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_23/bd_bdc1_sawn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_24/bd_bdc1_swn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_25/bd_bdc1_sbn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_29/bd_bdc1_s01a2s_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_30/bd_bdc1_sarn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_31/bd_bdc1_srn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_32/bd_bdc1_sawn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_33/bd_bdc1_swn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_34/bd_bdc1_sbn_1_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_35/bd_bdc1_m00s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_36/bd_bdc1_m00arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_37/bd_bdc1_m00rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_38/bd_bdc1_m00awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_39/bd_bdc1_m00wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_40/bd_bdc1_m00bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_42/bd_bdc1_m01s2a_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_43/bd_bdc1_m01arn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_44/bd_bdc1_m01rn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_45/bd_bdc1_m01awn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_46/bd_bdc1_m01wn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/bd_0/ip/ip_47/bd_bdc1_m01bn_0_ooc.xdc

# XDC: /home/esoc/Workspace/HJH/project_dma_wrapper/project_dma_wrapper.gen/sources_1/bd/ps_dma_ip/ip/ps_dma_ip_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dma_ip_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
