#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 13 13:46:33 KST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/linuxusr/tools/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axis_infrastructure_v1_1_1 -L axi4stream_vip_v1_1_19 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_19 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_layernorm_axi_wrapper_behav xil_defaultlib.tb_layernorm_axi_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axis_infrastructure_v1_1_1 -L axi4stream_vip_v1_1_19 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_19 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_layernorm_axi_wrapper_behav xil_defaultlib.tb_layernorm_axi_wrapper xil_defaultlib.glbl -log elaborate.log

